url: https://pcjordan.github.io
title: Philip's Blog
tagline: Title Yet To Be Found

plugins:
  - jekyll-seo-tag
  - jekyll-feed
navigation:
  - url: /index.html
    title: Home
  - url: /contact.html
    title: Contact
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      comments: true